build:
  base: /
  publish: out
  command: NODE_NO_WARNINGS=1 next dev --turbopack
  environment:
    NEXT_PUBLIC_SUPABASE_URL:
    NEXT_PUBLIC_SUPABASE_ANON_KEY:
    NEXT_PUBLIC_SOLANA_NETWORK: mainnet-beta
    NEXT_PUBLIC_SOLANA_RPC_URL: https://api.mainnet-beta.solana.com
    NEXT_PUBLIC_HELIUS_RPC_URL: https://mainnet.helius-rpc.com
    HELIUS_API_KEY: your-helius-api-key
    OPENAI_API_KEY: your-openai-api-key
    ANTHROPIC_API_KEY: your-anthropic-api-key
    COINGECKO_API_URL: https://api.coingecko.com/api/v3
    COINMARKETCAP_API_KEY: your-coinmarketcap-api-key
    TELEGRAM_BOT_TOKEN: your-telegram-bot-token
    TELEGRAM_BOT_USERNAME:
    DISCORD_BOT_TOKEN: your-discord-bot-token
    DISCORD_GUILD_ID:
    DISCORD_ROLE_ID:
    PRIVY_API_KEY: your-privy-api-key
    PRIVY_API_SECRET: your-privy-api-secret
    PRIVY_SIGNING_KEY:
    NEXT_PUBLIC_JUPITER_API_URL: https://quote-api.jup.ag/v1/quote
    NEXT_PUBLIC_EAP_RECEIVE_WALLET_ADDRESS: BARKkeAwhTuFzcLHX4DjotRsmjXQ1MshGrZbn1CUQqMo
    WALLET_ENCRYPTION_KEY:
    NEXT_PUBLIC_IMGBB_API_KEY:
    NFT_STORAGE_API_KEY:

deploy:
  command: "npm run deploy"
  environment:
    NEXT_PUBLIC_SOLANA_NETWORK: devnet
    NEXT_PUBLIC_SOLANA_RPC_URL: https://api.devnet.solana.com
    PRIVY_API_KEY: your-privy-api-key
    PRIVY_API_SECRET: your-privy-api-secret
    PRIVY_SIGNING_KEY:

plugins:
  - "@netlify/plugin-nextjs"
